server:
  port: 8085
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: hadoop_route # 标识路由的唯一标识，路由到 solr
          uri: http://localhost:8086 #需要转发到的地址
          # 断言规则
          predicates:
            - Path=/hadoop-server/**
          filters: # http://localhost:6666/hadoop-server/echo/aaa
            - StripPrefix=1 # 去除第一节
#   http://localhost:8086/echo/aaa
#        - id: stock_route

# gateway 配置


# 路由规则