#server:
#  port: 8085
#spring:
#  application:
#    name: cgh
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.111.90:8846
#      username: nacos
#      password: nacos
#      config:
#        server-addr: 192.168.111.90:8846
#        file-extension: yaml
#        namespace: public
#        refresh-enabled: true
#        extension-configs:
#          - dataId: db
#            refresh: true
#          - dataId: port
#            refresh: true
##            - RedirectTo=302,https://baidu.com
##            - PrefixPath=/hadoop
##            - PrefixPath=/hadoop
#
##        加入 sentinel 连接sentinel 服务地址。
##    sentinel:
##      transport:
##        dashboard: 127.0.0.1:8858
##   http://localhost:8086/echo/aaa
##        - id: stock_route
#
## gateway 配置
#
## 路由规则