server:
  port: 8086
spring:
  application:
    name: hadoop
  cloud:
    nacos:
      discovery:
        enabled: false
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.10.109:8848
#        namespace: public
#        password: nacos
