# 应用名称
spring:
  application:
    name: sentinel
      # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # nullCatalogMeansCurrent=true ，表示mysql默认当前数据库操作，在mysql-connector-java 5.xxx该参数默认为true，在6.xxx以上默认为false
    url: jdbc:mysql://192.168.111.90:3306/dev?uuseUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: dev
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
# 应用服务 WEB 访问端口
server:
  port: 8085

